In [1]:
# Sort ,Search & Counting Function 

In [3]:
import numpy as np 

In [5]:
arr = np.array([4,5,6,7,82,34,5,5,67,4])

In [6]:
arr

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [7]:
np.sort(arr)

array([ 4,  4,  5,  5,  5,  6,  7, 34, 67, 82])

In [8]:
np.searchsorted(arr,45)

8

In [9]:
arr1 = np.array([0,3435,45,0,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [12]:
np.where(arr>6)

(array([3, 4, 5, 8]),)

In [13]:
np.extract(arr>4 , arr)

array([ 5,  6,  7, 82, 34,  5,  5, 67])

In [14]:
# Numpy - Byte Swapping.

In [15]:
arr

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [16]:
arr.byteswap()

array([ 288230376151711744,  360287970189639680,  432345564227567616,
        504403158265495552, 5908722711110090752, 2449958197289549824,
        360287970189639680,  360287970189639680, 4827858800541171712,
        288230376151711744])

In [17]:
# Numpy - copies & views.

In [18]:
arr

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [21]:
a = np.copy(arr)

In [22]:
b = arr.view()

In [ ]:
b= arr

In [23]:
b

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [24]:
arr

array([ 4,  5,  6,  7, 82, 34,  5,  5, 67,  4])

In [25]:
# Nummpy - Matrix library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
# Numpy - Linear Algebra

In [41]:
arr1 = np.random.randint([[2,3],[4,5]])

In [42]:
arr2 = np.random.randint([[5,3],[2,5]])

In [43]:
np.dot(arr1,arr2)

array([[1, 2],
       [6, 8]])

In [44]:
arr1@arr2

array([[1, 2],
       [6, 8]])