In [2]:
#Numpy - Array Manipulation 

In [3]:
import numpy as np 

In [4]:
arr = np.random.randint(1,10, (3,4))

In [5]:
arr

array([[4, 3, 1, 2],
       [4, 3, 7, 3],
       [3, 7, 6, 4]])

In [6]:
arr.reshape(6,2)

array([[4, 3],
       [1, 2],
       [4, 3],
       [7, 3],
       [3, 7],
       [6, 4]])

In [7]:
arr.reshape(2,6)

array([[4, 3, 1, 2, 4, 3],
       [7, 3, 3, 7, 6, 4]])

In [8]:
arr.reshape(2,-2442)

array([[4, 3, 1, 2, 4, 3],
       [7, 3, 3, 7, 6, 4]])

In [9]:
arr.T

array([[4, 4, 3],
       [3, 3, 7],
       [1, 7, 6],
       [2, 3, 4]])

In [10]:
arr.flatten()

array([4, 3, 1, 2, 4, 3, 7, 3, 3, 7, 6, 4])

In [12]:
arr1 = np.array([1,2,3,4])

In [13]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1, axis =1 )

array([[1],
       [2],
       [3],
       [4]])

In [17]:
np.expand_dims(arr1, axis =0 )

array([[1, 2, 3, 4]])

In [18]:
arr

array([[4, 3, 1, 2],
       [4, 3, 7, 3],
       [3, 7, 6, 4]])

In [19]:
arr.squeeze(arr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [20]:
data = np.array([[1],[2],[3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 4])

In [24]:
np.repeat(arr1 ,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1 ,shift = 2)

array([3, 4, 1, 2])

In [27]:
arr1

array([1, 2, 3, 4])

In [28]:
np.roll(arr1 ,3)

array([2, 3, 4, 1])

In [29]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
#Numpy - Binary operation 

In [33]:
arr1 = np.random.randint(1,10,(3,4))

In [34]:
arr2 = np.random.randint(1,10,(3,4))

In [35]:
arr1

array([[5, 8, 4, 1],
       [1, 2, 6, 4],
       [9, 1, 9, 9]])

In [36]:
arr2

array([[9, 6, 5, 6],
       [3, 7, 6, 8],
       [6, 8, 2, 6]])

In [37]:
arr1 + arr2

array([[14, 14,  9,  7],
       [ 4,  9, 12, 12],
       [15,  9, 11, 15]])

In [38]:
arr1 * arr2

array([[45, 48, 20,  6],
       [ 3, 14, 36, 32],
       [54,  8, 18, 54]])

In [39]:
arr1/ arr2

array([[0.55555556, 1.33333333, 0.8       , 0.16666667],
       [0.33333333, 0.28571429, 1.        , 0.5       ],
       [1.5       , 0.125     , 4.5       , 1.5       ]])

In [40]:
arr1 - arr2

array([[-4,  2, -1, -5],
       [-2, -5,  0, -4],
       [ 3, -7,  7,  3]])

In [43]:
arr1%arr2

array([[5, 2, 4, 1],
       [1, 2, 0, 4],
       [3, 1, 1, 3]])

In [44]:
arr1** arr2

array([[1953125,  262144,    1024,       1],
       [      1,     128,   46656,   65536],
       [ 531441,       1,      81,  531441]])

In [45]:
arr1 & arr2

array([[1, 0, 4, 0],
       [1, 2, 6, 0],
       [0, 0, 0, 0]])

In [46]:
~arr1

array([[ -6,  -9,  -5,  -2],
       [ -2,  -3,  -7,  -5],
       [-10,  -2, -10, -10]])

In [47]:
arr1|arr2

array([[13, 14,  5,  7],
       [ 3,  7,  6, 12],
       [15,  9, 11, 15]])

In [48]:
arr1>arr2

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False,  True,  True]])

In [49]:
#Numpy - String Function 

In [51]:
arr   =np.array(['aditya' ,'kumar'])

In [52]:
arr

array(['aditya', 'kumar'], dtype='<U6')

In [53]:
np.char.upper(arr)

array(['ADITYA', 'KUMAR'], dtype='<U6')

In [54]:
np.char.title(arr)

array(['Aditya', 'Kumar'], dtype='<U6')

In [55]:
np.char.capitalize(arr)

array(['Aditya', 'Kumar'], dtype='<U6')

In [56]:
# Numpay - Mathematical Function 

In [57]:
np.sin(arr1)

array([[-0.95892427,  0.98935825, -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.90929743, -0.2794155 , -0.7568025 ],
       [ 0.41211849,  0.84147098,  0.41211849,  0.41211849]])

In [58]:
np.sin(arr1)

array([[-0.95892427,  0.98935825, -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.90929743, -0.2794155 , -0.7568025 ],
       [ 0.41211849,  0.84147098,  0.41211849,  0.41211849]])

In [59]:
np.tan(arr1)

array([[-3.38051501, -6.79971146,  1.15782128,  1.55740772],
       [ 1.55740772, -2.18503986, -0.29100619,  1.15782128],
       [-0.45231566,  1.55740772, -0.45231566, -0.45231566]])

In [60]:
np.log10(arr1)

array([[0.69897   , 0.90308999, 0.60205999, 0.        ],
       [0.        , 0.30103   , 0.77815125, 0.60205999],
       [0.95424251, 0.        , 0.95424251, 0.95424251]])

In [62]:
np.exp(arr1)

array([[1.48413159e+02, 2.98095799e+03, 5.45981500e+01, 2.71828183e+00],
       [2.71828183e+00, 7.38905610e+00, 4.03428793e+02, 5.45981500e+01],
       [8.10308393e+03, 2.71828183e+00, 8.10308393e+03, 8.10308393e+03]])

In [63]:
np.sqrt(arr1)

array([[2.23606798, 2.82842712, 2.        , 1.        ],
       [1.        , 1.41421356, 2.44948974, 2.        ],
       [3.        , 1.        , 3.        , 3.        ]])

In [64]:
np.power(arr1 ,2)

array([[25, 64, 16,  1],
       [ 1,  4, 36, 16],
       [81,  1, 81, 81]])

In [65]:
np.mean(arr1)

4.916666666666667

In [67]:
np.median(arr1)

4.5

In [68]:
np.std(arr1)

3.121386800054674

In [69]:
np.var(arr1)

9.743055555555555

In [70]:
np.min(arr1)

1

In [71]:
np.max(arr1)

9