In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b= np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
a= np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c = a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [22]:
c[0] =100

In [23]:
c

array([100,   2,   3,   4])

In [25]:
d = np.copy(a)

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a[1] = 400

In [29]:
a

array([100, 400,   3,   4])

In [30]:
d

array([100,   2,   3,   4])

In [31]:
np.fromfunction(lambda i, j : i ==j , (3,3,))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
iterable = ( i*i for i in range (5))

In [36]:
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('234 234' ,sep =' ')

array([234., 234.])

In [40]:
np.fromstring('4,5' ,sep =',')

array([4., 5.])

In [41]:
#Numpy -- Data  types. 

In [42]:
l = [2,3,4,5,6]

In [43]:
ar = np.array(l)

In [44]:
ar

array([2, 3, 4, 5, 6])

In [45]:
ar.ndim

1

In [46]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [47]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [48]:
ar2.ndim

2

In [49]:
ar.size

5

In [50]:
ar2.size

8

In [51]:
ar

array([2, 3, 4, 5, 6])

In [52]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [53]:
ar.shape

(5,)

In [54]:
ar2.shape

(2, 4)

In [56]:
ar.dtype

dtype('int64')

In [57]:
ar2.dtype

dtype('int64')

In [59]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [60]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [61]:
ar22.dtype

dtype('float64')

In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [65]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [68]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [69]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [75]:
ar4 =np.zeros((3,4,2,3))

In [76]:
ar4.ndim

4

In [77]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [78]:
np.ones(4)

array([1., 1., 1., 1.])

In [79]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
on = np.ones((2,3,2))

In [82]:
on +5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [83]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [84]:
np.empty((3,5))

array([[4.64574179e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [88]:
np.logspace(2,5,10 ,  base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [92]:
arr = np.random.randn(3,4)

In [93]:
import pandas as pd

In [94]:
pd.DataFrame(arr)

0         1         2         3
0 -0.563655 -1.279337 -0.013612  1.965229
1 -1.031763 -1.896713 -0.450781  0.711434
2  0.171114  0.853578 -0.545598 -0.383127

In [96]:
np.random.rand(3,4)

array([[0.45020891, 0.01724631, 0.35479989, 0.22806307],
       [0.55444923, 0.23363492, 0.90187556, 0.07942077],
       [0.11511151, 0.41740587, 0.07174885, 0.19230525]])

In [102]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [103]:
arr = np.random.rand(3,4)

In [104]:
arr

array([[0.33802817, 0.54349681, 0.52904065, 0.53508678],
       [0.7313605 , 0.64995387, 0.58492591, 0.84067981],
       [0.95750064, 0.89063271, 0.56910582, 0.29106672]])

In [108]:
arr1 = arr.reshape(6,-15241)

In [109]:
arr1

array([[0.33802817, 0.54349681],
       [0.52904065, 0.53508678],
       [0.7313605 , 0.64995387],
       [0.58492591, 0.84067981],
       [0.95750064, 0.89063271],
       [0.56910582, 0.29106672]])

In [110]:
arr1[1][1]

0.5350867751948698

In [112]:
arr1[2:5,1]

array([0.64995387, 0.84067981, 0.89063271])

In [114]:
arr = np.random.randint(1,100,(5,5))

In [115]:
arr

array([[57, 61, 47,  6, 23],
       [53, 90, 81, 96, 36],
       [36,  8, 86, 10, 36],
       [34, 50, 56, 58, 81],
       [66, 24, 54,  6, 91]])

In [117]:
arr[arr>50]

array([57, 61, 53, 90, 81, 96, 86, 56, 58, 81, 66, 54, 91])

In [118]:
arr

array([[57, 61, 47,  6, 23],
       [53, 90, 81, 96, 36],
       [36,  8, 86, 10, 36],
       [34, 50, 56, 58, 81],
       [66, 24, 54,  6, 91]])

In [119]:
arr[2:4 , [1,2]]

array([[ 8, 86],
       [50, 56]])

In [121]:
arr[0][0]=500

In [122]:
arr

array([[500,  61,  47,   6,  23],
       [ 53,  90,  81,  96,  36],
       [ 36,   8,  86,  10,  36],
       [ 34,  50,  56,  58,  81],
       [ 66,  24,  54,   6,  91]])

In [124]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [125]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [126]:
arr2

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [127]:
arr1 + arr2

array([[3, 3, 4],
       [2, 3, 2],
       [3, 3, 2]])

In [128]:
arr1 -arr2

array([[ 1,  1,  0],
       [ 0,  1,  0],
       [-1,  1,  0]])

In [129]:
arr1 / arr2

array([[2. , 2. , 1. ],
       [1. , 2. , 1. ],
       [0.5, 2. , 1. ]])

In [130]:
arr1*arr2

array([[2, 2, 4],
       [1, 2, 1],
       [2, 2, 1]])

In [131]:
arr1


array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [132]:
arr2

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [133]:
arr1@arr2

array([[8, 6, 8],
       [5, 4, 5],
       [5, 4, 5]])

In [134]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [135]:
arr1 +100

array([[102, 102, 102],
       [101, 102, 101],
       [101, 102, 101]])

In [136]:
arr1 **2

array([[4, 4, 4],
       [1, 4, 1],
       [1, 4, 1]])

In [137]:
# Numpy Broadcasting 

In [148]:
arr = np.zeros((4,4))

In [149]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
row = np.array([1,2,3,4])

In [151]:
row.shape

(4,)

In [152]:
row

array([1, 2, 3, 4])

In [153]:
arr+ row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
col = np.array([[1,2,3,4]]) 

In [157]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [158]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [159]:
arr1 = np.random.randint(1,4,(3,4))

In [160]:
arr1

array([[3, 2, 3, 2],
       [2, 3, 3, 2],
       [1, 3, 1, 1]])

In [161]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 1.73205081, 1.73205081, 1.41421356],
       [1.        , 1.73205081, 1.        , 1.        ]])

In [162]:
np.exp(arr1)

array([[20.08553692,  7.3890561 , 20.08553692,  7.3890561 ],
       [ 7.3890561 , 20.08553692, 20.08553692,  7.3890561 ],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183]])

In [163]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.        , 0.47712125, 0.        , 0.        ]])